language: cpp
matrix:
  include:
  - os: linux
    arch: amd64
    dist: focal
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y devscripts build-essential lintian dh-make autoconf lua-sql-postgres-dev automake gcc liblua5.2-dev libjansson-dev libcurl4-gnutls-dev libiniparser-dev libssl-dev libgd-dev libpng-dev libz3-dev libfreetype6-dev liblua5.1-dev libluajit-5.1-dev libgmp-dev
    compiler:
#    - clang
    - gcc
    script:
    - echo $TRAVIS_TAG
    - autoreconf -i 
    - ./configure
    - make
    after_script:
     addons:
     artifacts: true

before_install:
    - eval "${MATRIX_EVAL}"



